steps:
  - group: "Build"
    steps:
      - label: "Prepare build"
        command: echo "prepare build"

      - label: "Build"
        command: echo "run build"

  - group: "Test"
    steps:
      - label: "Prepare test"
        command: echo "prepare tests"

      - label: "Run tests"
        command: echo "run tests"
        command: echo "$build"
        if: build.pull_request.id != null || build.pull_request.draft
