steps:
  - group: "Build"
    steps:
      - label: "Prepare build"
        command: echo "prepare build"

      - label: "Build"
        command: echo "run build"

  - group: "Test"
    steps:
      - label: "Prepare tests"
        command: echo "prepare tests"
        
      - label: "Parallel test job with parallelism"
        parallelism: 2
        command: echo "running job $$BUILDKITE_PARALLEL_JOB out of $$BUILDKITE_PARALLEL_JOB_COUNT"
        
      - label: "Parallel test job with matrix: {{matrix}}"
        matrix:
          - "smoke-1"
          - "smoke-2"
        env:
          SUITE: "{{matrix}}"
          JOB_INDEX: "$$BUILDKITE_PARALLEL_JOB"
        command: echo "running $$SUITE, job $$JOB_INDEX $$BUILDKITE_PARALLEL_JOB out of $$BUILDKITE_PARALLEL_JOB_COUNT"

      - label: "Conditional tests run"
        commands: | 
          echo "run tests"
        if: "build.branch == 'main' || build.branch == 'bk-test-2' || (build.pull_request.id != null && !build.pull_request.draft)"
        
  - group: "External pipeline"
    steps: 
      - label: "Pipeline 2"
        command: buildkite-agent pipeline upload .buildkite/pipeline-2.yml
        
   
