steps:
  - group: "Build"
    steps:
      - label: "Prepare build"
        command: echo "prepare build"

      - label: "Build"
        command: echo "run build"

  - group: "Test"
    steps:
      - label: "Prepare tests"
        command: echo "prepare tests"

      - label: "Run tests"
        command: echo "run tests"
        if: build.branch == "master" || (build.pull_request.id != null && !build.pull_request.draft)
