name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  upload:
    name: "Upload an artifact"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: []

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Output something
        run: |
          mkdir -p output
          touch output/output.txt

      - name: "Upload"
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ matrix.version }}
          path: output

  download:
    name: "Download and use an artifact"
    runs-on: ubuntu-latest
    needs: [upload]

    steps:
      - name: "Download"
        uses: actions/download-artifact@v3
        with:
          path: download

      - name: "Check artifacts"
        run: pwd && ls -R
