name: Test
on:
  pull_request:
  push:
    branches:
      - main
  workflow_run:
    types: [ 'completed' ]
    workflows:
      - Build

jobs:
  run-tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12]
    env:
      EVENT_NAME: ${{ github.event_name }}
      SOME_SECRET: ${{ secrets.SOME_SECRET }}
      GITHUB_CONTEXT: ${{ toJson(github) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug
        run: | 
          echo $EVENT_NAME
          echo $SOME_SECRET
          echo $GITHUB_CONTEXT

      - name: Run on push
        if: ${{ env.EVENT_NAME == 'push' }}
        run: |
          echo "Run on push"
          mkdir -p test-results
          touch test-results/test-result-${{matrix.version}}.json

      - name: Run if secret is not set
        if: env.SOME_SECRET == ''
        run: echo "Missing secret"

      - name: Run if secret is set
        if: ${{ env.SOME_SECRET != '' }}
        run: echo "Secret is set"

      - name: Download artifacts
        if: github.event_name == 'workflow_run'
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: 0-build.yml
          workflow_conclusion: "success"
          run_id: ${{ github.event.workflow_run.id }}
          path: ../downloads

      - name: Download external artifacts
        if: github.event_name == 'workflow_run'
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: automattic/jetpack
          run_id: 3093614029
          workflow_conclusion: "success"
          path: build-output

      - name: Check downloaded artefacts
        if: github.event_name == 'workflow_run'
        run: |
          if [ "$GITHUB_EVENT_NAME" == workflow_run ]; then
            echo "Running tests on downloaded artifacts"
            ls -lh -R ../downloads
            ls -lh -R ./build-output
          else
            echo "Running tests on local build"
          fi

      - name: Extract build archive
        if: github.event_name == 'workflow_run'
        working-directory: ./build-output
        run: tar --xz -xvvf ./jetpack-build/build.tar.xz

      - name: Run tests
        if: github.event_name == 'workflow_run'
        working-directory: ./build-output/build
        run: |
          ls -lh -R

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'results-${{ strategy.job-index }}'
          path: 'test-results'

  report-flaky:
    name: "Report flaky tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: WordPress/gutenberg
          ref: dbf201449e9736f672b61e422787d47659db327a

      - run: |
          mkdir flaky-tests
          touch flaky-tests/the-flaky-test-report-of-test-one.json
          touch flaky-tests/the-flaky-test-report-of-test-two.json
          touch flaky-tests/the-flaky-test-report-of-test-three.json

      - uses: actions/upload-artifact@v4
        with:
          name: flaky-tests
          path: flaky-tests

      - uses: actions/download-artifact@v4
        id: download-artifact
        with:
          pattern: flaky-tests*
          path: flaky-tests
          merge-multiple: true

      - name: 'Check if there are flaky tests reports'
        run: |
          downloadPath='${{ steps.download-artifact.outputs.download-path }}'
          # make dir so that next step doesn't fail if it doesn't exist 
          mkdir -p $downloadPath
          ls -A -m $downloadPath
          echo "FLAKY_REPORTS=$(ls -A $downloadPath | head -1)" >> $GITHUB_ENV

      - name: 'Setup'
        if: ${{ !!env.FLAKY_REPORTS }}
        uses: ./.github/setup-node

      - name: 'Build'
        if: ${{ !!env.FLAKY_REPORTS }}
        run: npm run build:packages

      - name: 'Report flaky tests'
        if: ${{ !!env.FLAKY_REPORTS }}
        uses: ./packages/report-flaky-tests
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          label: 'flaky test'

  merge-artifacts:
    name: "Merge artifacts"
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: 'Merge artifacts'
        uses: actions/upload-artifact/merge@v4
        continue-on-error: true
        with:
          name: results-final
          pattern: results-*
          delete-merged: true
          
      - name: 'Download merged artifacts'
        uses: actions/download-artifact@v4
        with:
          nanme: results-final
          path: ./out

      - name: 'Check artifacts'
        run: ls -lhR .

      - name: 'Update artifacts'
        run: touch ./out/final.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'results-final'
          path: ./out
          ovewrite: true

