name: Test
on:
  pull_request:
  push:
    branches:
      - main
  workflow_run:
    types: [ 'completed' ]
    workflows:
      - Build

jobs:
  run-tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12]
    env:
      EVENT_NAME: ${{ github.event_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug
        run: echo $EVENT_NAME

      - name: Run on push
        if: $EVENT_NAME == 'push'
        run: echo "Run on push"

      - name: Download artifacts
        if: github.event_name == 'workflow_run'
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: 0-build.yml
          workflow_conclusion: "success"
          path: ../downloads

      - name: Download external artifacts
        if: github.event_name == 'workflow_run'
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: automattic/jetpack
          run_id: 3093614029
          workflow_conclusion: "success"
          path: build-output

      - name: Check downloaded artefacts
        if: github.event_name == 'workflow_run'
        run: |
          if [ "$GITHUB_EVENT_NAME" == workflow_run ]; then
            echo "Running tests on downloaded artifacts"
            ls -lh -R ../downloads
            ls -lh -R ./build-output
          else
            echo "Running tests on local build"
          fi

      - name: Extract build archive
        if: github.event_name == 'workflow_run'
        working-directory: ./build-output
        run: tar --xz -xvvf ./jetpack-build/build.tar.xz

      - name: Run tests
        if: github.event_name == 'workflow_run'
        working-directory: ./build-output/build
        run: ls -lh -R

