name: Test changes
on:
  pull_request:

jobs:
  upload:
    name: "Check diff"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/github-script@v7
        name: Check diff
        with:
          script: |
            const { execSync } = require('node:child_process');
            const output = execSync( `git diff --name-status origin/main`, {
                encoding: 'utf8',
            } );
            console.log(output.split( '\n' ));
