name: Test changes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  upload:
    name: "Check diff"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/github-script@v7
        name: Check diff
        with:
          script: |
            const diff = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            console.log(diff.data.base.sha, '...', diff.data.head.sha);
