name: Cron test

on:
  schedule:
    - cron: '*/15 * * * *'
    - cron: '*/20 * * * *'
    
jobs:
  test-cron:
      name: "Tests cron"
      runs-on: ubuntu-latest
      timeout-minutes: 1
      steps:
        - uses: actions/checkout@v2

        - name: Check cron
          id: check-cron
          env:
            CRON: github.event.schedule
          run: test-cron.sh
