name: Test with Environments
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run on any event
        run: |
          echo "Run on any event"
          mkdir -p test-results
          touch test-results/test-result-${{matrix.version}}.json

      - name: Run on push
        if: ${{ env.EVENT_NAME == 'push' }}
        run: |
          echo "Run on push"

      - name: Run on pull_request
        if: ${{ env.EVENT_NAME == 'push' }}
        run: |
          echo "Run on pull_request"

      - name: Run on workflow_dispatch
        if: ${{ env.EVENT_NAME == 'push' }}
        run: |
          echo "Run on workflow_dispatch"
