name: Test matrix

on:
  push:

jobs:
  matrix-job:
    name: "Run with ${{ matrix.group }} matrix value"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: [ 'pre-connection', 'connection', 'post-connection', 'gutenberg' ]
    
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Run ${{ matrix.group }} tests
      run: |
        
        if [ ${{ matrix.group }} == "gutenberg" ]; then echo "GUTENBERG=latest" >> $GITHUB_ENV; fi
        echo "$GUTENBERG"
        echo ${{ env.GUTENBERG }}
