name: Test matrix

on:
  push:

concurrency:
  group: matrix-${{ github.event_name }}-${{ github.ref }}-${{ github.event.action }}
  cancel-in-progress: true

jobs:
  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      jobs1: ${{ steps.evaluate.outputs.jobs1 }}
      jobs2: ${{ steps.evaluate.outputs.jobs2 }}
    steps:
    - name: Create matrix
      id: evaluate
      run: |
          JOBS1='[{name: "job1.1", optional: true},{name: "job1.2", optional: false},{name: "job1.3", optional: false}]'
          JOBS2='[{name: "job2.1", optional: false},{name: "job2.2", optional: false},{name: "job2.3", optional: true}]'
          echo "jobs1=$JOBS1" >> "$GITHUB_OUTPUT"
          echo "jobs2=$JOBS2" >> "$GITHUB_OUTPUT"

  matrix-job:
    name: "Run ${{ matrix.name }}"
    runs-on: ubuntu-latest
    needs: [create-matrix]
    outputs:
      evaluation: ${{ steps.evaluate.run.evaluation }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson( needs.create-matrix.outputs.matrix )}}

    steps:
    - uses: actions/checkout@v4

    - name: Set env value
      run: |
        echo "Name: ${{matrix.name}}"
        echo "Id: ${{matrix.id}}"
        if [ ${{ matrix.id }} == 1 ]; then echo "MATRIX_1=true" >> $GITHUB_ENV; fi
#        if [[ ${{ matrix.name }} == *matrix ]]; then echo "matrix tests"; fi

    - name: Run ${{ matrix.name }} tests
      id: run
      env:
        RUN_ID: ${{ matrix.id }}
      run: |
        sleep ${{ matrix.id }}

        echo ${{strategy.job-index}}

        echo "$MATRIX_1"
        echo ${{ env.MATRIX_1 }}
        echo $RUN_ID >> metadata.json
        cat metadata.json
        
        # fail fail fail
        if [ ${{ matrix.id }} == 2 ]; then exit 1; fi

        # Write output
        echo "evaluation={\"key\":\"value\"}" >> "$GITHUB_OUTPUT"

  conditional-job:
    name: "Report"
    runs-on: ubuntu-latest
    if: ${{ success() || failure() }}
    needs: [matrix-job]

    steps:
    - uses: actions/checkout@v4

    - name: Notify
      run: |
        echo ${{ needs.matrix-job.result }}
  
  evaluate-job:
    name: "Evaluate"
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [matrix-job]
    env:
      NEEDS_CTX: ${{ fromJSON(needs.matrix-job.outputs) }}

    steps:
    - name: Evaluate
      run: |
        result="${{ needs.*.result }}"
        echo $result
        echo $NEEDS_CTX
        if [[ $result != "success" && $result != "skipped" ]]; then
          echo "One or more needed jobs have failed."
          exit 1
        fi