name: Test matrix

on:
  push:

jobs:
  matrix-job:
    name: "Run with ${{ matrix.group }} matrix value"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: [ 'pre-connection', 'post-connection' ]
    env:
      GUTENBERG: bundle
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Set env value
      run: |
        if [ ${{ matrix.group }} == gutenberg ]; then echo "GUTENBERG=latest" >> $GITHUB_ENV; fi
    
    - name: Run ${{ matrix.group }} tests
      run: |
        echo ${{ toJson(matrix) }}
        echo "$GUTENBERG"
        echo ${{ env.GUTENBERG }}
        # if [ ${{ matrix.group }} == gutenberg ]; then exit 1; fi
  
  conditional-job:
    name: "Report"
    runs-on: ubuntu-latest
    needs: matrix-job
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Notify
      run: |
        echo 'I ran because the previous job was successful'
        echo ${{ needs.matrix-job.result }}
  
