name: Test matrix with evaluation

on:
  push:

concurrency:
  group: matrix-${{ github.event_name }}-${{ github.ref }}-${{ github.event.action }}
  cancel-in-progress: true

jobs:
  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      jobs1: ${{ steps.evaluate.outputs.jobs1 }}
      jobs2: ${{ steps.evaluate.outputs.jobs2 }}
    steps:
    - name: Create matrix
      id: evaluate
      run: |
          JOBS1='[{name: "job1.1", optional: true}]'
          JOBS2='[{name: "job2.1", optional: false}]'
          echo "jobs1=$JOBS1" >> "$GITHUB_OUTPUT"
          echo "jobs2=$JOBS2" >> "$GITHUB_OUTPUT"

  matrix-job-1:
    name: "Run 1 - ${{ matrix.name }}"
    runs-on: ubuntu-latest
    needs: [create-matrix]
    outputs:
      evaluation: ${{ steps.evaluate.run.evaluation }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson( needs.create-matrix.outputs.jobs1 )}}

    steps:
    - name: Run
      run: |
        echo "Name: ${{matrix}}"

  matrix-job-2:
    name: "Run 2 - ${{ matrix.name }}"
    runs-on: ubuntu-latest
    needs: [create-matrix]
    outputs:
      evaluation: ${{ steps.evaluate.run.evaluation }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson( needs.create-matrix.outputs.jobs2 )}}

    steps:
    - name: Run
      run: |
        echo "Name: ${{matrix}}"
  
  evaluate-job:
    name: "Evaluate"
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [matrix-job-1, matrix-job-2]

    steps:
    - name: Evaluate
      run: |
        echo "needs context: ${{ toJson(needs) }}"

        result=${{needs.*.result}}
        echo $result
        if [[ $result != "success" && $result != "skipped" ]]; then
          echo "One or more needed jobs have failed."
          exit 1
        fi