name: Paths tests

on:
  push:
    paths:
      - 'src/folder_one/**'

jobs:
  test-paths-job:
    name: "folder_one changed"
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Echo stuff
      run: echo 'folder_one changed'
  
