name: Test pm2

on:
  push:
    branches: [main]

jobs:
  test-pm2:
    name: "Tests pm2 process"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install
        run: |
          yarn install

      - name: Start tunnel
        run: |
          yarn tunne-on
          yarn pm2 logs --nostream

      - name: Check output
        run: |
          cat tunnel-url

      - name: Stop tunnel
        run: |
          yarn tunnel-off
          yarn pm2 logs --nostream
