name: Test pm2

on:
  push:
    branches: [main]

jobs:
  test-pm2:
    name: "Tests pm2 process"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Install and run pm2
      run: |
        yarn install
        yarn pm2-tunnel
        cat /home/runner/.pm2/pm2.log

    - name: Check output
      run: cat tunnel-url
