name: 'Pull Request target'
on:
    pull_request_target:
        types:
            - opened
            - reopened
            - synchronize
concurrency:
    group: label-pr-${{ github.event_name }}-${{ github.event.action }}-${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.ref || github.run_id }}
    cancel-in-progress: true

permissions: {}

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo ${{github.event_name}}
                echo $${{github.event.pull_request.head.ref}}
                echo ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.ref }}
                echo label-pr-${{ github.event_name }}-${{ github.event.action }}-${{ github.event.pull_request.head.ref }}