name: Playwright tests
on:
  push:

jobs:
  upload:
    name: "Run tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install
        run: | 
          npm install
          npm exec playwright install

      - name: Download last run info
        id: 'download-last-run-info'
        uses: actions/download-artifact@v4
        with:
          pattern: 'last-run__${{ strategy.job-index }}.json'

      - name: Run tests
        run: |
          # Move and rename the downloaded file to the expected name
          echo "download step output: ${{ steps.download-last-run-info.outputs.download-path }}"
          ls -lha "${{ steps.download-last-run-info.outputs.download-path }}"
          downloadedFile="${{ steps.download-last-run-info.outputs.download-path }}/.last-run__${{ strategy.job-index }}.json"
          lastRunFilePath="test-results/.last-run.json"
          if [[ -f "$downloadedFile" ]]; then
            echo "Found last run info file: \"$downloadedFile\""
            ls -lha "${{ steps.download-last-run-info.outputs.download-path }}"
            mv "$downloadedFile" "$lastRunFilePath"
            ls -lha test-results
          else
            echo "No last run info file found. Searched for: \"$downloadedFile\""
          fi
          
          lastRunFlag=""
          if [ -f "$lastRunFilePath" ]; then
            cat "$lastRunFilePath"
            # Playwright last run info is available, parse the file and check if there are failed tests
            failedTests=$(jq '.failedTests | length' "$lastRunFilePath")
          
            # Only if there are failed tests, we want to use the --last-failed flag. 
            # The run will fail if we're using the flag and there are no failed tests.
            if [ "$failedTests" -gt 0 ]; then
              echo "Found failed tests, running only failed tests"
              lastRunFlag="--last-failed"
            fi
          fi
          
          echo "Running tests. Last run flag: $lastRunFlag" 
          npm run test $lastRunFlag
          

      - name: Upload last run info
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'last-run__${{ strategy.job-index }}.json'
          path: 'test-results/.last-run.json'
          if-no-files-found: ignore
          overwrite: true
