name: Playwright tests
on:
  push:

jobs:
  upload:
    name: "Run tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install
        run: | 
          npm install
          npm exec playwright install

      - name: Run tests
        run: npm run test

      - name: Upload last run info
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: '.last-run__${{ strategy.job-index }}.json'
          path: 'test-results/.last-run.json'
          if-no-files-found: ignore
          overwrite: true
