name: Repository dispatch

on:
  push:
  workflow_dispatch:

jobs:
  run-tests:
    name: "Trigger e2e tests in other repo"
    runs-on: ubuntu-latest
    if: github.repository == 'adimoldovan/sandbox'

    steps:
      - name: Create a repository dispatch
        uses: peter-evans/repository-dispatch@v2
        env:
          EVENT_TYPE: e2e tests at ${{github.event_name}} on ${{github.repository}} ${{github.ref_name}} ${{github.ref_type}}
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: adimoldovan/sandbox2
          event-type: ${{ env.EVENT_TYPE }}
          client-payload: '{"repository": "${{github.repository}}", "ref_name": "${{github.ref_name}}", "ref_type": "${{github.ref_type}}", "sha": "${{github.sha}}"}'
