name: Repository dispatch

on:
  push:
  workflow_dispatch:

jobs:
  run-tests:
    name: "Trigger e2e tests in other repo"
    runs-on: ubuntu-latest
    if: github.repository == 'adimoldovan/sandbox'

    steps:
      - name: Set environment
        run: |
          echo "EVENT_TYPE=$GITHUB_RUN_ID at $GITHUB_EVENT_NAME on $GITHUB_REPOSITORY" >> "$GITHUB_ENV"
        
      - name: Create a repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: adimoldovan/sandbox2
          event-type: ${{ env.EVENT_TYPE }}
          client-payload: '{"repository": "${{github.repository}}", "ref_name": "${{github.ref_name}}", "ref_type": "${{github.ref_type}}", "sha": "${{github.sha}}"}'
