name: Test secrets
on:
  push:
    branches:
      - main

jobs:
  check-secrets:
    name: "Check secrets"
    runs-on: ubuntu-latest
    env:
      EVENT_NAME: ${{ github.event_name }}
      VALID_SECRET: ${{ secrets.VALID_SECRET }}
      MISSING_SECRET: ${{ secrets.MISSING_SECRET }}

    steps:
      - name: Debug
        run: | 
          echo $EVENT_NAME
#          echo $VALID_SECRET
#          echo $MISSING_SECRET
          echo ${{toJSON(secrets)}}

      - name: Run on push
        if: ${{ env.EVENT_NAME == 'push' }}
        run: echo "Run on push"

      - name: Run if MISSING_SECRET is not set
        if: env.MISSING_SECRET == ''
        run: echo "MISSING_SECRET is not set"

      - name: Run if VALID_SECRET is set
        if: ${{ env.VALID_SECRET != '' }}
        run: echo "VALID_SECRET is set"

