name: Slack
on:
  pull_request: 
  push:
    branches:
      - main 

jobs:
  first-job:
    name: "Firs job before Slack notification"
    runs-on: ubuntu-latest
    steps:
      - name: "Step one"
        run: echo "Hello"

  second-job:
    name: "Second job before Slack notification"
    runs-on: ubuntu-latest
    steps:
      - name: "Step one"
        run: echo "Hello"

  parallel-job:
    name: "Parallel with Slack notification"
    runs-on: ubuntu-latest
    needs: [second-job]
    steps:
      - name: "Step one"
        run: echo "Hello, I run in parallel"

  slack-notification:
    name: "Send notification"
    runs-on: ubuntu-latest
    needs: [second-job]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Action
        run: |
          npm install
          npm run build
        working-directory: ./.github/actions/slack

      - name: "Run the action"
        uses: ./.github/actions/slack
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }}