name: Steps test

on:
  push:

jobs:
  multiple-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run some bash commands
        run: |
          EXIT_CODE=0
          bash ./.github/workflows/fail.sh || EXIT_CODE=$?
          echo $EXIT_CODE
          echo "I ran after a failed commad"
          exit $EXIT_CODE
