name: Steps test

on:
  push:

jobs:
  multiple-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        run: |
          ./fail.sh
          echo "I ran after a failed commad"
