name: Test env variables

on:
  push:

jobs:
  env-variables:
    name: "Check env variables"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [ 'group 1', 'group 2' ]
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Print env variables for ${{ matrix.group }}
      run: |
        echo $GITHUB_WORKFLOW
        echo $GITHUB_EVENT_PATH
        echo $GITHUB_EVENT_NAME
        echo $GITHUB_REF
        echo $GITHUB_HEAD_REF
        echo $GITHUB_BASE_REF
        echo $GITHUB_RUN_ID
        
    - name: Upload event.json
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.event_path }}
