name: Test env and context

on:
  push:
  
  schedule:
    - cron: '0 0 10 * *'
    
  pull_request:

jobs:
  env-variables:
    name: "Check env variables"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [ 'group 1', 'group 2' ]
        
    steps:
    - uses: actions/checkout@v2
    
    - name: "Check repo name"
      if: github.repository == 'AdiMolDoVan/SanDBox'
      run: |
        echo ${{ github.repository }}
        echo "It's a match!"

    - name: Print env variables for ${{ matrix.group }}
      run: |
        echo "GITHUB_WORKFLOW $GITHUB_WORKFLOW"
        echo "GITHUB_EVENT_PATH $GITHUB_EVENT_PATH"
        echo "GITHUB_EVENT_NAME $GITHUB_EVENT_NAME"
        echo "GITHUB_REF $GITHUB_REF"
        echo "GITHUB_HEAD_REF $GITHUB_HEAD_REF"
        echo "GITHUB_BASE_REF GITHUB_BASE_REF"
        echo "GITHUB_RUN_ID $GITHUB_RUN_ID"
        echo "GITHUB_ACTION $GITHUB_ACTION"
        echo "GITHUB_JOB $GITHUB_JOB"
        echo "GITHUB_TRIGGERING_ACTOR $GITHUB_TRIGGERING_ACTOR"
        DIFF="$(jq -r '"\( .pull_request.base.sha )...\( .pull_request.head.sha )"' "$GITHUB_EVENT_PATH")"
        echo "$DIFF"
        
    - name: Upload event.json
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.event_path }}

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo "PR number: ${{ github.event.pull_request.number }}"
        wcho "Commit message: ${{ github.event.head_commit.message }}"
        echo "Ref: ${{ github.ref }}"

